### PR TITLE
ISPN-7062 - Cassandra cache store: Upgrade to latest cassandra and Da…

### PR DESCRIPTION
**Pull request by oscerd**
…tastax driver

Hi all,

This PR is related to: https://issues.jboss.org/browse/ISPN-7062

Thanks,
Andrea

### CODE REVIEW

**Comment by burmanm** [comment]
Newest Cassandra is 3.9, but it might be recommendable to use the 3.0.9 version instead if stability is important (unless newer features of 3.x are used)

**Comment by oscerd** [comment]
Yeah, I guess you're right. 3.9 is a tick-tock release. I'm upgrading the PR :-)

**Comment by oscerd** [comment]
At least we should stay with 3.2.

**Comment by tristantarrant** [comment]
I agree with @burmanm: let's use 3.0.10

**Comment by oscerd** [comment]
I guess this is will need some work on the code.

**Comment by burmanm** [comment]
Is there something in the code that would require 3.x? I didn't see such commits and the only major feature missing from 3.0.x is SASI (but SASI isn't used here).

**Comment by oscerd** [comment]
Not sure, but If you try to build the current code with 3.0.10 the build will fail during test, because the cassandra client didn't connect to the Cassandra instance. That's why I was suggesting to use 3.2.

Anyway I'll take a deeper look when I'll have time.

**Comment by burmanm** [comment]
Ah, try updating the cassandra-driver to newer version in the branch (but keep it separate from the Cassandra version, they're two different things). 3.0.6 is the newest driver version, that should at least work (we use 3.0.5 in the Hawkular to connect to 3.0.x Cassandra versions - but we just haven't noticed the new version 3.0.6).

**Comment by oscerd** [comment]
Tested with cassandra 3.0.10 and cassandra driver 3.0.5 and 3.0.6 but no luck.

**Comment by burmanm** [comment]
What's the error? It shouldn't be the versions.

**Comment by burmanm** [comment]
Sounds more like environment issue ;)

**Comment by oscerd** [comment]
It was a problem with a new option in cassandra.yaml, I'll push a new PR in minutes :-)

**Comment by oscerd** [comment]
thanks @burmanm

**Comment by oscerd** [comment]
PR updated

**Comment by oscerd** [comment]
@tristantarrant @burmanm let me know what you think

**Comment by tristantarrant** [comment]
Merged, thanks

**Pull request closed without merging**
