### PR TITLE
Configuration improvements

### PR DESCRIPTION
**Pull request by jmarkos**
https://issues.jboss.org/browse/ISPN-7052
https://issues.jboss.org/browse/ISPN-7053
https://issues.jboss.org/browse/ISPN-7054
https://issues.jboss.org/browse/ISPN-7055
https://issues.jboss.org/browse/ISPN-7056

Would be nice if also Антон Борисов could look at this, I'll try to notify him on JIRA since I don't know his github username.

### CODE REVIEW

**Comment by jmarkos** [comment]
I simply missed setting the consistency levels for selectAll/delete statements, will fix that.

Compression configuration can have more options, like "{ 'sstable_compression' : 'DeflateCompressor', 'chunk_length_kb' : 64 }" (see http://docs.datastax.com/en/cassandra/3.x/cassandra/operations/opsConfigCompress.html), so what you propose wouldn't be enough.

For the replication strategy, the full 'cassandra-style string' gives us some future compatibility, so I'd rather not mirror their configuration one to one.

**Comment by jmarkos** [comment]
Fixed the consistency levels on selectAll and delete statements & checkstyle violations.

**Comment by tristantarrant** [comment]
Needs rebase

**Comment by jmarkos** [comment]
Rebased. Some tests were failing, so I created and fixed https://issues.jboss.org/browse/ISPN-7432.

**Comment by galderz** [comment]
Looks good, integrating

**Pull request merged**
